# Generated by Django 3.1.1 on 2021-03-30 19:14

from django.db import migrations, models
import django.db.models.deletion
import pay.models.session


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0054_shopdesign_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(default=pay.models.session.generate_uid, max_length=255)),
                ('paid_at', models.DateTimeField(null=True)),
                ('cancel_url', models.URLField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
