  version: '3'
    
  services:
    web:
      build: .
      command: sh ./docker-entrypoint.sh
      volumes:
        - .:/usr/src/app
      ports:
        - "5000:5000"
      env_file:
        - ./.env
      depends_on:
        - "redis"

    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
      volumes:
        - ~/data/redis:/data
