  version: '3'
    
  services:
    web:
      build: .
      command: sh ./docker-entrypoint.sh
      volumes:
        - .:/usr/src/app
      ports:
        - "5000:5000"
      env_file:
        - ./.env
      depends_on:
        - "redis"

    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data

    caddy:
      image: caddy:2.0.0-alpine
      ports:
        - 80:80
        - 443:443
      volumes:
        - caddy_data:/data
        - caddy_config:/config
        - ./Caddyfile:/etc/caddy/Caddyfile

  volumes:
    caddy_data:
    caddy_config:
    redis_data:
