[tool.poetry]
name = "api"
version = "0.1.0"
description = "Kweek's api"
authors = ["Nelson Kamga <kamganelson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
alembic = "1.4.2"
ariadne = "0.12.0"
boto3 = "1.14.47"
botocore = "1.17.47"
cachecontrol = "0.12.6"
cachetools = "4.1.1"
certifi = "2020.6.20"
cffi = "1.14.2"
chardet = "3.0.4"
click = "7.1.2"
docutils = "0.15.2"
firebase-admin = "4.3.0"
flask-cors = "3.0.8"
flask-jwt-extended = "3.24.1"
flask-migrate = "2.5.3"
flask-sqlalchemy = "2.4.4"
flask = "1.1.2"
google-api-core = {version = "1.22.1", extras = ["grpc"]}
google-api-python-client = "1.10.0"
google-auth-httplib2 = "0.0.4"
google-auth = "1.20.1"
google-cloud-core = "1.4.1"
google-cloud-firestore = "1.8.1"
google-cloud-storage = "1.30.0"
google-crc32c = "0.1.0"
google-resumable-media = "0.7.1"
googleapis-common-protos = "1.52.0"
graphql-core = "3.0.5"
graphqlclient = "0.2.4"
grpcio = "1.31.0"
gunicorn = "20.0.4"
httplib2 = "0.18.1"
huey = "2.3.0"
idna = "2.10"
itsdangerous = "1.1.0"
jinja2 = "2.11.2"
jmespath = "0.10.0"
mako = "1.1.3"
markupsafe = "1.1.1"
msgpack = "1.0.0"
pendulum = "2.1.2"
protobuf = "3.13.0"
psycopg2-binary = "2.8.5"
pyasn1-modules = "0.2.8"
pyasn1 = "0.4.8"
pycparser = "2.20"
pyjwt = "1.7.1"
python-dateutil = "2.8.1"
python-dotenv = "0.14.0"
python-editor = "1.0.4"
pytz = "2020.1"
pytzdata = "2020.1"
redis = "3.5.3"
requests = "2.24.0"
rsa = "4.6"
s3transfer = "0.3.3"
six = "1.15.0"
slackclient = "1.3.2"
sqlalchemy = "1.3.19"
starlette = "0.13.8"
typing-extensions = "3.7.4.3"
uritemplate = "3.0.1"
urllib3 = "1.25.10"
websocket-client = "0.54.0"
werkzeug = "1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
