# Generated by Django 3.1.1 on 2020-09-09 00:11
from django.contrib.auth.hashers import make_password
from django.db import migrations


def set_passwords(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        user.password = make_password(None)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200909_0010"),
    ]

    operations = [migrations.RunPython(set_passwords)]
