# Generated by Django 3.1.1 on 2020-09-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200909_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_units',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='weight in kilograms'),
            preserve_default=False,
        ),
    ]
