# Generated by Django 3.1.1 on 2020-09-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200911_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='avatar',
        ),
    ]
