# Generated by Django 3.1.1 on 2020-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200912_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Credit or debit card')], default='card', max_length=10),
        ),
    ]
