# Generated by Django 3.1.1 on 2020-09-13 18:35

from django.db import migrations

from core.models.checkout import generate_checkout_ref


def fill_checkout_ref_id(apps, schema_editor):
    Checkout = apps.get_model("core", "Checkout")
    for checkout in Checkout.objects.all():
        checkout.ref_id = generate_checkout_ref()
        checkout.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200913_1834'),
    ]

    operations = [
        migrations.RunPython(fill_checkout_ref_id)
    ]
