# Generated by Django 3.1.1 on 2020-09-13 18:49

import core.models.checkout
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200913_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='ref_id',
            field=models.CharField(default=core.models.checkout.generate_checkout_ref, max_length=40, unique=True),
        ),
    ]
