# Generated by Django 3.1.1 on 2020-09-13 19:33

import core.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200913_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(default=core.models.order.generate_order_id, max_length=40, unique=True),
        ),
    ]
