# Generated by Django 3.1.1 on 2020-09-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200913_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cover_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
