# Generated by Django 3.1.1 on 2020-09-16 14:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200916_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateagent',
            name='commission',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.08000000000000000166533453693773481063544750213623046875'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.shop'),
        ),
    ]
