# Generated by Django 3.1.1 on 2020-09-16 15:34

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200916_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateagent',
            name='code',
            field=models.CharField(default=core.models.base.generate_affiliate_code, max_length=10, unique=True),
        ),
    ]
