# Generated by Django 3.1.1 on 2021-01-07 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200916_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
