# Generated by Django 3.1.1 on 2021-01-07 11:04

from django.db import migrations

def add_domains(apps, schema_editor):
    Shop = apps.get_model("core", "Shop")
    for shop in Shop.objects.all():
        shop.domains.append(f"{shop.username}.kweek.shop")
        shop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shop_domains'),
    ]

    operations = [
        migrations.RunPython(add_domains)
    ]
