# Generated by Django 3.1.1 on 2021-02-12 13:45

from django.db import migrations

def fix_usernames(apps, schema_editor):
    Shop = apps.get_model("core", "Shop")
    for shop in Shop.objects.filter(username__contains="_"):
        shop.username = shop.username.replace("_", "-")
        shop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210107_1104'),
    ]

    operations = [
        migrations.RunPython(fix_usernames)
    ]
