# Generated by Django 3.1.1 on 2021-02-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210212_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Credit or debit card'), ('cash', 'Cash on delivery')], default='card', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Credit or debit card'), ('cash', 'Cash on delivery')], default='card', max_length=10),
        ),
    ]
