# Generated by Django 3.1.1 on 2021-02-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210212_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='shop',
            name='country_code',
            field=models.CharField(default='BJ', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='currency_iso',
            field=models.CharField(default='XOF', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
