# Generated by Django 3.1.1 on 2021-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210217_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currency_iso',
            new_name='old_currency_iso',
        ),
        migrations.AlterField(
            model_name='shop',
            name='currency_iso',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
