# Generated by Django 3.1.1 on 2021-03-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210222_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('account_bank', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=4)),
                ('rave_subaccount_id', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=15)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
