# Generated by Django 3.1.1 on 2021-03-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='country',
        ),
    ]
