# Generated by Django 3.1.1 on 2021-03-05 17:21

from django.db import migrations


def add_shop_to_carts(apps, schema_editor):
    Shop = apps.get_model("core", "Shop")
    Cart = apps.get_model("core", "Cart")
    for cart in Cart.objects.all():
        cart.shop = Shop.objects.filter(products__in=cart.products.all()).distinct().first()
        cart.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_cart_shop'),
    ]

    operations = [
        migrations.RunPython(add_shop_to_carts)
    ]
