# Generated by Django 3.1.1 on 2021-03-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210305_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDesign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagline', models.CharField(max_length=225)),
                ('hero_cta', models.CharField(max_length=100)),
                ('instagram_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='core.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
