# Generated by Django 3.1.1 on 2021-03-11 19:09

from django.db import migrations


def add_design_to_shop(apps, schema_editor):
    Shop = apps.get_model("core", "Shop")
    ShopDesign = apps.get_model("core", "ShopDesign")
    for shop in Shop.objects.all():
        ShopDesign.objects.create(
            tagline="Découvrez nos meilleurs produits et collections",
            hero_cta="Shoppez maintenant",
            shop=shop
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_shopdesign'),
    ]

    operations = [
        migrations.RunPython(add_design_to_shop)
    ]
