# Generated by Django 3.1.1 on 2021-03-21 17:49
# Generated by Django 3.1.1 on 2021-03-21 17:45

from django.db import migrations
from djmoney.money import Money


def fill_prices_cart_items(apps, schema_editor):
    CartItem = apps.get_model("core", "CartItem")
    for item in CartItem.objects.filter(product__isnull=False).all():
        item.price = Money(item.product.price, item.product.shop.currency_iso)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210321_1749'),
    ]

    operations = [
        migrations.RunPython(fill_prices_cart_items)
    ]
