# Generated by Django 3.1.1 on 2021-03-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210321_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='old_price',
        ),
    ]
