# Generated by Django 3.1.1 on 2021-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210321_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='new_price_currency',
            new_name='price_currency',
        ),
    ]
