# Generated by Django 3.1.1 on 2021-03-21 21:29

from django.db import migrations
from djmoney.money import Money


def create_shipping_profiles(apps, schema_editor):
    ShippingProfile = apps.get_model('core', "ShippingProfile")
    ShippingZone = apps.get_model('core', "ShippingZone")
    ShippingMethod = apps.get_model('core', "ShippingMethod")
    Shop = apps.get_model('core', "Shop")

    futurix = ShippingProfile.objects.create(
        name="Futurix Logistics",
        avatar_url="https://kweek-api.s3.amazonaws.com/futurix-logo.png",
        profile_type="manual",
    )
    cotonou = ShippingZone.objects.create(
        name="Cotonou",
        profile=futurix
    )
    calavi = ShippingZone.objects.create(
        name="Calavi",
        profile=futurix
    )
    porto = ShippingZone.objects.create(
        name="Porto-Novo",
        profile=futurix
    )
    ShippingMethod.objects.create(
        zone=cotonou,
        price=Money(1000, "XOF"),
        name="Standard",
        description="1-2 jours"
    )
    ShippingMethod.objects.create(
        zone=calavi,
        price=Money(1500, "XOF"),
        name="Standard",
        description="1-2 jours"
    )
    ShippingMethod.objects.create(
        zone=porto,
        price=Money(2000, "XOF"),
        name="Standard",
        description="2-3 jours"
    )

    dhl = ShippingProfile.objects.create(
        name="DHL Express",
        avatar_url="https://kweek-api.s3.amazonaws.com/dhl.png",
        profile_type="auto",
        backend="core.backends.shipping.DHLExpressBackend"
    )

    for shop in Shop.objects.all():
        futurix.shops.add(shop)
        dhl.shops.add(shop)


def delete_shipping_profiles(apps, schema_editor):
    ShippingProfile = apps.get_model('core', "ShippingProfile")
    ShippingProfile.objects.filter(
        name__in=["DHL Express", "Futurix Logistics"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0042_auto_20210321_2128'),
    ]

    operations = [
        migrations.RunPython(create_shipping_profiles, delete_shipping_profiles)
    ]
