# Generated by Django 3.1.1 on 2021-03-21 22:55

from django.db import migrations
from djmoney.money import Money


def migrate_shipping_option(apps, schema_editor):
    Checkout = apps.get_model('core', "Checkout")
    ShippingProfile = apps.get_model('core', "ShippingProfile")
    for checkout in Checkout.objects.all():
        if checkout.shipping_option:
            option = checkout.shipping_option.get('name')
            price = checkout.shipping_option.get('price')
            checkout.shipping_profile = ShippingProfile.objects.get(
                name="DHL Express" if 'dhl' in option.lower() else 'Futurix Logistics')
            checkout.shipping_fees = Money(price.get('amount'), price.get('currency'))
            checkout.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0044_auto_20210321_2255'),
    ]

    operations = [
        migrations.RunPython(migrate_shipping_option)
    ]
