# Generated by Django 3.1.1 on 2021-03-21 23:07

from django.db import migrations
from moneyed import Money


def migrate_shipping_option(apps, schema_editor):
    Order = apps.get_model('core', "Order")
    ShippingProfile = apps.get_model('core', "ShippingProfile")
    for order in Order.objects.all():
        if order.shipping_option:
            option = order.shipping_option.get('name')
            price = order.shipping_option.get('price')
            order.shipping_profile = ShippingProfile.objects.get(
                name="DHL Express" if 'dhl' in option.lower() else 'Futurix Logistics')
            order.shipping_fees = Money(price.get('amount'), price.get('currency'))
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210321_2307'),
    ]

    operations = [
        migrations.RunPython(migrate_shipping_option)
    ]
