# Generated by Django 3.1.1 on 2021-03-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210321_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
