# Generated by Django 3.1.1 on 2021-03-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210323_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='products', to='core.Category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_category_name_per_shop'),
        ),
    ]
