# Generated by Django 3.1.1 on 2021-03-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210323_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
