# Generated by Django 3.1.1 on 2021-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210324_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='zone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
