# Generated by Django 3.1.1 on 2021-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210324_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdesign',
            name='theme',
            field=models.CharField(default='storefront', max_length=255),
        ),
    ]
