# Generated by Django 3.1.1 on 2021-03-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_shopdesign_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdesign',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
