# Generated by Django 3.1.1 on 2021-05-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210402_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='affiliate',
        ),
        migrations.DeleteModel(
            name='AffiliateAgent',
        ),
    ]
