version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
    command: sh ./docker-entrypoint.sh
    volumes:
      - app_data:/usr/src/app
    ports:
      - "4040:5000"
    depends_on:
      - "redis"
      - "postgres"

  celery:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
    command: celery -A app_main worker -l warning
    volumes:
     - app_data:/usr/src/app
    depends_on:
     - "web"
     - "redis"
     - "postgres"

  celery-beat:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
    command: celery -A app_main beat -l warning
    volumes:
     - app_data:/usr/src/app
    depends_on:
     - "web"
     - "redis"
     - "postgres"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  redis_data:
  db_data:
  app_data:
