version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    command: sh ./docker-entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "4040:5000"
    depends_on:
      - "redis"
      - "postgres"

  celery:
    build: .
    command: celery -A app_main worker -l warning
    volumes:
     - .:/usr/src/app
    depends_on:
     - "web"
     - "redis"
     - "postgres"

  celery-beat:
    build: .
    command: celery -A app_main beat -l warning
    volumes:
     - .:/usr/src/app
    depends_on:
     - "web"
     - "redis"
     - "postgres"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  redis_data:
