version: '3'

services:
  celery:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    command: celery -A app_main worker -l warning
    restart: unless-stopped
    volumes:
     - ../../:/usr/src/app

  celery-beat:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    command: celery -A app_main beat -l warning
    restart: unless-stopped
    volumes:
     - ../../:/usr/src/app

  flower:
    build:
      context: ../../
      dockerfile: deploy/prod/Dockerfile
    command: celery -A app_main flower --port=5555
    restart: unless-stopped
    volumes:
      - ../../:/usr/src/app
    ports:
      - "5555:5555"
    depends_on:
      - "celery"
      - "celery-beat"
