version: '3'

services:
  web:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    command: sh ./docker-entrypoint.sh
    volumes:
      - ../../:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - "redis"

  celery:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    command: celery -A app_main worker -l warning
    volumes:
     - ../../:/usr/src/app
    depends_on:
     - "web"
     - "redis"

  celery-beat:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    command: celery -A app_main beat -l warning
    volumes:
     - ../../:/usr/src/app
    depends_on:
     - "web"
     - "redis"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
