# Generated by Django 3.1.1 on 2022-05-22 17:18

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kash_card', '0003_refundhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundhistory',
            name='usd_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='refundhistory',
            name='xof_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='XOF', max_digits=17, null=True),
        ),
    ]
