version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: deploy/beta/Dockerfile
    command: sh ./docker-entrypoint.sh
    volumes:
      - ../../:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
      - "postgres"

  celery:
    build:
      context: ../../
      dockerfile: deploy/beta/Dockerfile
    command: celery -A app_main worker -l warning
    volumes:
     - ../../:/usr/src/app
    depends_on:
     - "web"
     - "redis"
     - "postgres"

  celery-beat:
    build:
      context: ../../
      dockerfile: deploy/beta/Dockerfile
    command: celery -A app_main beat -l warning
    volumes:
     - ../../:/usr/src/app
    depends_on:
     - "web"
     - "redis"
     - "postgres"

  flower:
    build:
      context: ../../
      dockerfile: deploy/beta/Dockerfile
    command: celery -A app_main flower --port=5555
    volumes:
      - ../../:/usr/src/app
    ports:
      - "5555:5555"
    depends_on:
      - "celery"
      - "celery-beat"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  redis_data:
  db_data:
