"""Initial migration.

Revision ID: 4380f3fb215c
Revises: 
Create Date: 2020-08-24 17:00:00.567586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4380f3fb215c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'banner', ['id'])
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_unique_constraint('uniq_category_id', 'category', ['id'])
    op.add_column('product', sa.Column('currency_iso', sa.String(length=10), nullable=False, server_default="XOF"))
    op.create_unique_constraint('uniq_product_id', 'product', ['id'])
    op.drop_constraint('product_shop_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'sold')
    op.create_unique_constraint('uniq_product_image_id', 'product_image', ['id'])
    op.drop_constraint('product_image_product_id_fkey', 'product_image', type_='foreignkey')
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('shop', sa.Column('phone_number', sa.String(length=255)))
    op.execute('UPDATE shop SET phone_number=whatsapp_number')
    op.alter_column('shop', 'phone_number', nullable=False)
    op.alter_column('shop', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('shop_user_id_key', 'shop', type_='unique')
    op.create_unique_constraint('uniq_shop_id', 'shop', ['id'])
    op.drop_constraint('shop_user_id_fkey', 'shop', type_='foreignkey')
    op.create_foreign_key(None, 'shop', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_firebase_id_key', 'user', type_='unique')
    op.drop_constraint('user_phone_number_key', 'user', type_='unique')
    op.create_unique_constraint('uniq_user_id', 'user', ['id'])
    op.drop_column('user', 'firebase_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_phone_number_key', 'user', ['phone_number'])
    op.create_unique_constraint('user_firebase_id_key', 'user', ['firebase_id'])
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.create_foreign_key('shop_user_id_fkey', 'shop', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'shop', type_='unique')
    op.create_unique_constraint('shop_user_id_key', 'shop', ['user_id'])
    op.alter_column('shop', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('shop', 'phone_number')
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.create_foreign_key('product_image_product_id_fkey', 'product_image', 'product', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'product_image', type_='unique')
    op.add_column('product', sa.Column('sold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_foreign_key('product_shop_id_fkey', 'product', 'shop', ['shop_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'currency_iso')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'banner', type_='unique')

    # ### end Alembic commands ###
