# Generated by Django 3.1.1 on 2022-03-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kash_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField()),
                (
                    'profile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='verification_methods',
                        to='kash_user.userprofile',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
