# Generated by Django 3.1.1 on 2022-03-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash_auth', '0001_initial'),
    ]

    operations = []
