# Generated by Django 3.1.1 on 2022-03-17 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kash.auth.models.verification_attempt


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kash_user", "0001_initial"),
        ("kash_auth", "0002_auto_20220307_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationmethod",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_methods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verificationmethod",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_methods",
                to="kash_user.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="verificationmethod",
            name="type",
            field=models.CharField(
                choices=[("phone", "Phone"), ("email", "Email")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="VerificationAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "security_code",
                    models.CharField(
                        default=kash.auth.models.verification_attempt.generate_security_code,
                        max_length=120,
                    ),
                ),
                ("session_token", models.CharField(max_length=500)),
                ("is_verified", models.BooleanField(default=False)),
                ("value", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("phone", "Phone"), ("email", "Email")], max_length=20
                    ),
                ),
                (
                    "verification_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_attempt",
                        to="kash_auth.verificationmethod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
