# Generated by Django 3.1.1 on 2022-03-17 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kash_auth", "0003_auto_20220317_2206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationmethod",
            name="profile",
        ),
        migrations.AlterField(
            model_name="verificationattempt",
            name="value",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="verificationmethod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_methods",
                to="kash_user.user",
            ),
        ),
    ]
