# Generated by Django 3.1.1 on 2022-03-18 10:54

from django.db import migrations


def migrate_existing_verified_phone(apps, schema_editor):
    User = apps.get_model("kash_user", "User")
    VerificationMethod = apps.get_model("kash_auth", "VerificationMethod")
    for user in User.objects.exclude(phone_number=""):
        VerificationMethod.objects.create(
            type="phone", value=user.phone_number, is_verified=True, user=user
        )


class Migration(migrations.Migration):

    dependencies = [
        ("kash_auth", "0004_auto_20220317_2335"),
    ]

    operations = [migrations.RunPython(migrate_existing_verified_phone)]
