# Generated by Django 3.1.1 on 2022-03-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kash_auth", "0005_auto_20220318_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationmethod",
            name="value",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="verificationmethod",
            constraint=models.UniqueConstraint(
                fields=("user", "value", "is_verified"),
                name="unique_verified_verificationmethod",
            ),
        ),
    ]
