# Generated by Django 3.1.1 on 2022-04-21 23:47

from django.db import migrations, models
import kash.abstract.models


class Migration(migrations.Migration):

    dependencies = [
        ('kash_payout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=kash.abstract.models.generate_ref_id, max_length=12, unique=True)),
                ('amount', models.IntegerField()),
                ('ngn_payin_status', models.CharField(default='pending', max_length=200)),
                ('xof_txn_status', models.CharField(default='pending', max_length=200)),
                ('usd_txn_status', models.CharField(default='pending', max_length=200)),
                ('xof_txn_ref', models.CharField(blank=True, max_length=255)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
