# Generated by Django 3.1.1 on 2022-04-22 00:14

from django.db import migrations, models
import django.db.models.deletion
import kash.abstract.models


class Migration(migrations.Migration):

    dependencies = [
        ('kash_card', '0002_auto_20220315_2155'),
        ('kash_payout', '0002_auto_20220421_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=kash.abstract.models.generate_ref_id, max_length=12, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('action_type', models.CharField(choices=[('funding', 'Funding'), ('withdrawal', 'Withdrawal')], max_length=100)),
                ('amount', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kash_card.virtualcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
