# This is a basic workflow to help you get started with Actions

name: Deploy to staging

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.BETA_SSH_HOST }}
          USERNAME: ${{ secrets.BETA_SSH_USERNAME }}
          KEY: ${{ secrets.BETA_SSH_PRIVATE_KEY }}
        with:
          source: "."
          target: "~/apps/kash-api"

      - name: Deployment
        uses: appleboy/ssh-action@v0.1.4
        env:
          ENV_VAR: ${{secrets.BETA_ENV_VAR}}
        with:
          host: ${{ secrets.BETA_SSH_HOST }}
          key: ${{ secrets.BETA_SSH_PRIVATE_KEY }}
          username: ${{ secrets.BETA_SSH_USERNAME }}
          script: |
            cd ~/apps/kash-api
            echo "${{ secrets.BETA_ENV_VAR }}" > .env
            sudo docker-compose up -d --build

