# Generated by Django 3.1.1 on 2021-03-31 19:45

from django.db import migrations, models
import django.db.models.deletion
import kash.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('gateway', models.CharField(choices=[('MOOV MONEY', 'moov'), ('MTN MOBILE MONEY', 'mtn')], max_length=20)),
                ('reference', models.CharField(default=kash.utils.generate_reference_10, max_length=20, unique=True)),
                ('service_reference', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('refunded', 'refunded')], default='pending', max_length=40)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=17)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=45)),
                ('service_message', models.CharField(max_length=512, null=True)),
                ('last_status_checked', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'qosic_transaction',
            },
        ),
    ]
