# Generated by Django 3.1.1 on 2021-04-02 15:37

import django.core.validators
from django.db import migrations, models
import kash.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0004_auto_20210402_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kashtag',
            field=models.CharField(max_length=30, unique=True, validators=[kash.models.user_profile.KashtagValidator, django.core.validators.MinLengthValidator(3)]),
        ),
    ]
