# Generated by Django 3.1.1 on 2021-04-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0009_auto_20210404_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kashtransaction',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='kashtransaction',
            old_name='total_currency',
            new_name='amount_currency',
        ),
    ]
