# Generated by Django 3.1.1 on 2021-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0010_auto_20210404_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('payout', 'Payout')], default='payment', max_length=10),
        ),
    ]
