# Generated by Django 3.1.1 on 2021-04-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0011_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('moov-bj', 'moov'), ('mtn-bj', 'mtn')], max_length=20)),
                ('phone', models.CharField(max_length=45)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='kash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
