# Generated by Django 3.1.1 on 2021-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0015_kashrequestresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='kashtransaction',
            name='paid_recipients',
            field=models.ManyToManyField(to='kash.UserProfile'),
        ),
    ]
