# Generated by Django 3.1.1 on 2021-04-06 13:10

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0018_auto_20210406_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinghistory',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='XOF', max_digits=17),
        ),
    ]
