# Generated by Django 3.1.1 on 2021-04-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0019_auto_20210406_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
