# Generated by Django 3.1.1 on 2021-04-06 18:42

from django.db import migrations, models
import django.db.models.deletion
import kash.models.invite_code


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0020_virtualcard_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=kash.models.invite_code.generate_code, max_length=10, unique=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kash.userprofile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='kash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
