# Generated by Django 3.1.1 on 2021-04-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0021_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kash.userprofile'),
        ),
    ]
