# Generated by Django 3.1.1 on 2021-04-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0022_auto_20210406_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invited',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='kash.userprofile'),
        ),
    ]
