# Generated by Django 3.1.1 on 2021-04-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0030_auto_20210413_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayoutMethod',
            new_name='MomoAccount',
        ),
    ]
