# Generated by Django 3.1.1 on 2021-04-20 16:44

from django.db import migrations, models
import kash.utils


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0030_auto_20210413_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=kash.utils.generate_reference_10, max_length=50, unique=True),
        ),
    ]
