# Generated by Django 3.1.1 on 2021-04-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0032_auto_20210415_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='kashrequest',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='kashrequest',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kash.userprofile'),
        ),
        migrations.AddField(
            model_name='kashrequest',
            name='rejected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
