# Generated by Django 3.1.1 on 2021-04-15 23:35

from django.db import migrations

def forward(apps, schema_editor):
    KashRequest = apps.get_model('kash', "KashRequest")
    KashRequestResponse = apps.get_model('kash', "KashRequestResponse")
    for request in KashRequest.objects.all():
        if request.recipients.count() == 1:
            response = KashRequestResponse.objects.filter(
                sender_id=request.recipients.first().id,
                request_id=request.id
            ).first()
            request.recipient = request.recipients.first()
            if response:
                if response.accepted:
                    request.accepted_at = response.created_at
                else:
                    request.rejected_at = response.created_at
                request.created_at = response.created_at
            request.save()
        else:
            for recipient in request.recipients.all():
                new_request = KashRequest.objects.create(
                    recipient=recipient,
                    initiator=request.initiator,
                    note=request.note,
                    amount=request.amount,
                )
                response = KashRequestResponse.objects.filter(
                    sender_id=recipient.id,
                    request_id=request.id
                ).first()
                new_request.recipient = recipient
                if response:
                    if response.accepted:
                        new_request.accepted_at = response.created_at
                    else:
                        new_request.rejected_at = response.created_at
                    new_request.created_at = response.created_at
                new_request.save()
            request.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0034_auto_20210415_2334'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
