# Generated by Django 3.1.1 on 2021-04-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0036_auto_20210415_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kashtransaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kash_transactions', to='kash.userprofile'),
        ),
        migrations.AlterField(
            model_name='sendkash',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kash_sent', to='kash.userprofile'),
        ),
    ]
