# Generated by Django 3.1.1 on 2021-04-19 17:05

from django.db import migrations


def forward(apps, schema_editor):
    KashTransaction = apps.get_model('kash', "KashTransaction")
    Transaction = apps.get_model('kash', "Transaction")
    for kash_txn in KashTransaction.objects.all():
        kash_txn.txn = Transaction.objects.get(reference=kash_txn.txn_ref)
        kash_txn.save()


class Migration(migrations.Migration):
    dependencies = [
        ('kash', '0038_kashtransaction_txn'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
