# Generated by Django 3.1.1 on 2021-04-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0039_auto_20210419_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kashtransaction',
            name='txn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kash.transaction'),
        ),
    ]
