# Generated by Django 3.1.1 on 2021-04-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0041_kycdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdocument',
            old_name='id_doc_url',
            new_name='doc_url',
        ),
        migrations.RenameField(
            model_name='kycdocument',
            old_name='id_document_type',
            new_name='document_type',
        ),
    ]
