# Generated by Django 3.1.1 on 2021-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0042_auto_20210420_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.ManyToManyField(to='kash.UserProfile'),
        ),
    ]
