# Generated by Django 3.1.1 on 2021-04-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0043_userprofile_contacts'),
        ('kash', '0031_auto_20210420_1644'),
    ]

    operations = [
    ]
