# Generated by Django 3.1.1 on 2021-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0044_merge_20210421_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendkash',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
