# Generated by Django 3.1.1 on 2021-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0045_auto_20210423_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='kashtransaction',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sendkash',
            name='note',
            field=models.TextField(),
        ),
    ]
