# Generated by Django 3.1.1 on 2021-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0046_auto_20210425_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('payout', 'Payout'), ('refund', 'Refund')], default='payment', max_length=10),
        ),
    ]
