# Generated by Django 3.1.1 on 2021-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0047_auto_20210426_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
