# Generated by Django 3.1.1 on 2021-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0048_kycdocument_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='doc_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='selfie_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
