# Generated by Django 3.1.1 on 2021-05-15 22:17

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0049_auto_20210503_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='kash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
