# Generated by Django 3.1.1 on 2021-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0052_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='memo',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
