# Generated by Django 3.1.1 on 2021-06-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0053_auto_20210524_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
