# Generated by Django 3.1.1 on 2021-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0054_virtualcard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
