# Generated by Django 3.1.1 on 2021-07-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0056_cardtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransaction',
            name='narration',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='product',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='reference_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='txn_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
