# Generated by Django 3.1.1 on 2021-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0058_virtualcard_last_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalhistory',
            name='status',
            field=models.CharField(choices=[('paid-out', 'Paid Out'), ('failed', 'Failed'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], default='success', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='txn_ref',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
