# Generated by Django 3.1.1 on 2021-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0059_auto_20210726_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalhistory',
            name='txn_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
