# Generated by Django 3.1.1 on 2021-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0062_auto_20210806_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provider_name',
            field=models.CharField(choices=[('dummy', 'Dummy'), ('qosic', 'Qosic')], default='qosic', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('moov-bj', 'Moov'), ('mtn-bj', 'Mtn')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=40),
        ),
    ]
