# Generated by Django 3.1.1 on 2021-08-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0064_virtualcard_provider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcard',
            name='service',
        ),
    ]
