# Generated by Django 3.1.1 on 2021-08-26 08:09

from django.db import migrations, models
import django.db.models.deletion
import kash.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0065_remove_virtualcard_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default=kash.models.user_profile.generate_code, max_length=10),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rewarded_at', models.DateTimeField(null=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kash.userprofile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='kash.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
