# Generated by Django 3.1.1 on 2021-08-26 20:29

from django.db import migrations, models
import kash.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0067_auto_20210826_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reward_reference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default=kash.models.user_profile.generate_code, max_length=10, unique=True),
        ),
    ]
