# Generated by Django 3.1.1 on 2021-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0068_auto_20210826_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='promo_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('value', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('applied_to', models.ManyToManyField(to='kash.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
