# Generated by Django 3.1.1 on 2021-09-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0071_transaction_discount_accounted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='reward_reference',
        ),
    ]
