# Generated by Django 3.1.1 on 2021-10-16 14:49

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0072_remove_referral_reward_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPayoutRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=core.models.base.generate_ref_id, max_length=12, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
