# Generated by Django 3.1.1 on 2022-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0074_earning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=17)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
