# Generated by Django 3.1.1 on 2022-01-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0075_rates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rates',
            new_name='Rate',
        ),
    ]
