# Generated by Django 3.1.1 on 2022-02-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0076_auto_20220112_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinghistory',
            name='is_funding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_name',
            field=models.CharField(choices=[('dummy', 'Dummy'), ('qosic', 'Qosic')], default='dummy', max_length=20),
        ),
    ]
